version: "3.8"
services:
  weaviate:
    image: semitechnologies/weaviate:latest
    container_name: weaviate
    environment:
      - QUERY_DEFAULTS_LIMIT=20
      - ENABLE_MODULES=text2vec-transformers
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED="true"
    ports:
      - "8080:8080"
    volumes:
      - weaviate_data:/weaviate/db
    restart: always

volumes:
  weaviate_data:

